version: '3.8'

services:
  web:
    image: bidnamic_web
    volumes:
      - static:/static
    build: .
    restart: always
    ports:
      - "8000:8000"
      # - "587:587"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  nginx:
    image: nginx
    pull_policy: always
    restart: always
    volumes:
      - static:/static
    ports:
      - "80:80"
      
volumes:
  static:

