version: '3.8'

services:
  web:
    image: bidnamic_web
    volumes:
      - static:/static
      - media:/media 
    build: .
    restart: always
    ports:
      - "8000:8000"
      # - "587:587"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

volumes:
  static:
  media:

