version: '3.8'

services:
  web:
    image: bidnamic_web
    volumes:
      - static:/static
      - media:/media 
    build: .
    restart: always
    ports:
      - "8000:8000"
      # - "587:587"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  database:
    restart: always
    image: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    # expose:
    #    - 5432     

volumes:
  static:
  media: