name: Run Tests
on: push

jobs:
  bidnamic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: experiments
    env:
      POSTGRES_DB: django
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: bidnamic
      DB_PASSWORD: bidnamic
      POSTGRES_HOST_AUTH_METHOD: trust      
      DB_HOST: localhost
    services:
      postgres:
        image: postgres:14.0
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: django
          DB_USER: bidnamic
          DB_PASSWORD: bidnamic
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py migrate
        python3 manage.py test